services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: shermadmin
      POSTGRES_PASSWORD: shermpass
      POSTGRES_DB: shermmap
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sherm-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DATABASE_URL: postgres://shermadmin:shermpass@db:5433/shermmap
      JWT_SECRET: supersecretkey
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads   # damit Uploads persistent sind      